# conjur policy load cd/kubernetes cd/kubernetes/k8s-secrets-app.yml

- !policy
  id: k8s-secrets-app
  owner: !group admins
  annotations:
    description: Kubernetes application retrieving secrets using Kubernetes Secrets push method
    kubernetes: true
  body:
    - !host
      annotations:
        authn-k8s/namespace: cyberark-conjur
        authn-k8s/service-account: k8s-secrets-provider-account
        authn-k8s/authentication-container-name: cyberark-secrets-provider
        kubernetes: true
